In [7]:
%load_ext autoreload
%autoreload 2

In [8]:
from transformers import RobertaModel, RobertaTokenizer
from bertviz import model_view, head_view

In [9]:
# model_version = 'seyonec/PubChem10M_SMILES_BPE_396_250'
model_name = "DeepChem/ChemBERTa-77M-MTR"
model = RobertaModel.from_pretrained(model_name, output_attentions=True)
tokenizer = RobertaTokenizer.from_pretrained(model_name)

Some weights of the model checkpoint at DeepChem/ChemBERTa-77M-MTR were not used when initializing RobertaModel: ['regression.out_proj.weight', 'regression.dense.bias', 'norm_mean', 'regression.dense.weight', 'norm_std', 'regression.out_proj.bias']
- This IS expected if you are initializing RobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of RobertaModel were not initialized from the model checkpoint at DeepChem/ChemBERTa-77M-MTR and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions an

## TOKENIZER


In [10]:
# smiles = "CN1C=NC2=C1C(=O)N(C(=O)N2C)C" # Caffeine
# smiles = "C1=CC=CC=C1"  # Benzene
smiles = "CN=C=O"

# smiles = "CNC1CC(c2ccc(Cl)c(Cl)c2)c2ccccc21"

# basic_tokens = tokenizer.basic_tokenizer.tokenize(smiles)
tokens = tokenizer.tokenize(smiles)

# print(basic_tokens)
print(tokens)

['C', 'N', '=', 'C', '=', 'O']


In [11]:
# Get tokenizer output
inputs = tokenizer(smiles, return_tensors="pt", add_special_tokens=True)
input_ids = inputs["input_ids"]
# attention = model(input_ids)[-1]
input_id_list = input_ids[0].tolist()
tokens = tokenizer.convert_ids_to_tokens(input_id_list)
tokens

['[CLS]', 'C', 'N', '=', 'C', '=', 'O', '[SEP]']

In [16]:
from thesis_work.chemberta.model_descriptors import (
    get_model_descriptors,
    get_model_descriptor,
)

# combine_strategy = None
combine_strategy = "mean"
# combine_strategy = "concat"

model_descriptors = get_model_descriptors(
    smiles_series=[smiles],
    model_name=model_name,
    method="simpletransformers",
    combine_strategy=combine_strategy,
    device="cuda",
)
print(model_descriptors.shape)
model_descriptors

(1, 384)


array([[ 6.44680977e-01, -1.01943326e+00,  2.87657231e-01,
         2.15444595e-01, -6.85453176e-01, -7.41437554e-01,
        -5.92899084e-01,  9.47463870e-01, -3.69819939e-01,
        -7.13435590e-01,  4.76380855e-01, -2.69500226e-01,
         7.62101650e-01, -9.21040922e-02, -1.98557720e-01,
         3.96829814e-01,  4.13297206e-01,  9.13170040e-01,
        -1.27736449e+00,  1.26813710e-01,  6.86327040e-01,
        -7.95256644e-02,  1.14956252e-01, -7.31052041e-01,
        -6.57008216e-03, -2.14511901e-03,  3.97483438e-01,
        -9.82641101e-01, -3.81026417e-02,  4.00525570e-01,
         5.31020761e-01, -1.74761534e-01,  8.74967575e-01,
        -6.53599128e-02, -5.04253387e-01,  2.20991671e-01,
        -1.50480819e+00,  3.02432418e-01, -1.65274012e+00,
        -9.95334089e-02,  3.82094570e-02, -4.88264352e-01,
        -3.47997159e-01, -1.29533589e+00, -3.52550685e-01,
        -5.71334958e-02,  8.56676251e-02, -1.32095009e-01,
         8.80584598e-01,  1.72419146e-01, -5.45640707e-0

In [13]:
import torch

# Create a tensor of shape (3, 4) with random values
x = torch.randn(3, 4)

print(x.shape)

# Compute the mean of the tensor along the first dimension
mean = torch.mean(x, dim=0)

# Print the original tensor and the mean tensor
print("Original tensor:\n", x)
print("Mean tensor:\n", mean)

torch.Size([3, 4])
Original tensor:
 tensor([[ 0.1507,  0.4252, -0.3881, -0.2430],
        [-1.2987, -0.4613,  0.4731,  0.4309],
        [ 0.6500, -0.5809, -1.6235,  0.5523]])
Mean tensor:
 tensor([-0.1660, -0.2057, -0.5128,  0.2468])


In [15]:
get_model_descriptor(model=model, tokenizer=tokenizer, smiles_str=smiles)

array([-1.61976844e-01,  9.48189557e-01, -1.64082972e-04,  1.86998606e-01,
       -1.66552052e-01, -1.84483409e-01,  2.78902620e-01,  5.49632777e-03,
        8.26953411e-01, -6.20257974e-01,  2.37295076e-01, -1.58038586e-01,
        9.46547464e-02,  4.81336951e-01, -4.25404042e-01, -1.15184993e-01,
        4.38077524e-02,  2.55751908e-01, -3.54016304e-01, -1.04702443e-01,
       -1.48847759e-01, -3.72610152e-01,  2.21171096e-01, -4.62652922e-01,
       -6.43651128e-01, -3.93063515e-01,  2.30660751e-01, -6.14330173e-02,
        2.96609879e-01,  3.75875592e-01, -2.81843785e-02,  4.66140002e-01,
       -1.23960912e-01,  4.26484406e-01,  6.21499181e-01,  6.55578375e-02,
        1.23361036e-01,  8.69583860e-02,  1.36210844e-01, -2.74521500e-01,
       -2.49515802e-01, -1.06298491e-01, -2.26081461e-02, -2.92534947e-01,
        3.50420684e-01,  1.86305910e-01,  3.02701294e-02, -6.75851926e-02,
       -2.05602050e-01,  2.73242772e-01, -3.50459777e-02,  6.52147174e-01,
       -2.60669976e-01, -

## MODEL VIEW


In [2]:
%%javascript
require.config({
  paths: {
      d3: '//cdnjs.cloudflare.com/ajax/libs/d3/5.7.0/d3.min',
    jquery: '//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min',
  }
});

<IPython.core.display.Javascript object>

In [3]:
sentence_a = "CCCCC[C@@H](Br)CC"
sentence_b = "CCCCC[C@H](Br)CC"

inputs = tokenizer.encode_plus(
    sentence_a, sentence_b, return_tensors="pt", add_special_tokens=True
)
input_ids = inputs["input_ids"]
attention = model(input_ids)[-1]
input_id_list = input_ids[0].tolist()  # Batch index 0
tokens = tokenizer.convert_ids_to_tokens(input_id_list)
model_view(attention, tokens)

Some weights of the model checkpoint at DeepChem/ChemBERTa-77M-MLM were not used when initializing RobertaModel: ['lm_head.decoder.bias', 'lm_head.layer_norm.weight', 'lm_head.layer_norm.bias', 'lm_head.bias', 'lm_head.dense.bias', 'lm_head.dense.weight', 'lm_head.decoder.weight']
- This IS expected if you are initializing RobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of RobertaModel were not initialized from the model checkpoint at DeepChem/ChemBERTa-77M-MLM and are newly initialized: ['roberta.pooler.dense.weight', 'roberta.pooler.dense.bias']
You should probably TRAIN this model on a down-stream task to be 

<IPython.core.display.Javascript object>

In [5]:
head_view(attention, tokens)

<IPython.core.display.Javascript object>

In [3]:
import statistics

values = [0.15, 0.17, 0.12, 0.16, 0.20, 0.07, 0.26]
# values = [-0.03, 0.04, 0.05, -0.1, -0.20, 0.07, 0.06]

mean = statistics.mean(values)
std_dev = statistics.stdev(values)

print("Mean:", mean)
print("Standard deviation:", std_dev)

Mean: -0.015714285714285715
Standard deviation: 0.10146545271784922
